In [113]:
import numpy as np
import pandas as pd
from sklearn import metrics

In [114]:
# importing dataset
dataset = pd.read_csv('Iris.csv')
X = dataset.iloc[:, :-1].values # X is the Independent Variable
y = dataset.iloc[:, -1].values  # y is the Dependent Variable 
dataset.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [115]:
# splitting train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
# Training Dataset is 75% and Testing Dataset is 25% 

In [116]:
print(X_train[:5])

[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]]


In [117]:
print(y_train[:5])

['Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica']


In [118]:
print(X_test[:5])

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]]


In [119]:
print(y_test[:5])

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa']


In [120]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [121]:
print(X_train[:5])

[[ 0.01543995 -0.11925475  0.22512685  0.35638175]
 [-0.09984503 -1.04039491  0.11355956 -0.02864805]
 [ 1.05300481 -0.11925475  0.95031423  1.12644135]
 [-1.36797986  0.34131533 -1.39259884 -1.31208072]
 [ 1.1682898   0.11103029  0.72717965  1.38312788]]


In [122]:
print(X_test[:5])

[[-0.09984503 -0.57982483  0.72717965  1.51147115]
 [ 0.13072494 -1.96153508  0.11355956 -0.28533458]
 [-0.44569998  2.64416573 -1.33681519 -1.31208072]
 [ 1.62942973 -0.34953979  1.39658338  0.74141155]
 [-1.0221249   0.80188541 -1.28103155 -1.31208072]]


In [123]:
# training the model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, X_train)

GaussianNB()

In [124]:
# predicting for one input
SepalLengthCm = input("Enter The Sepal Length: ")
SepalWidthCm = input("Enter The Sepal Width: ")
PetalLengthCm = input("Enter The Petal Length: ")
PetalWidthCm = input("Enter The Petal Width: ")
print(classifier.predict(sc.transform([[SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm]])))

Enter The Sepal Length: 6
Enter The Sepal Width: 2.12
Enter The Petal Length: 2
Enter The Petal Width: 4
['Iris-virginica']


In [125]:
# predicting the values for test set
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']


In [126]:
# finding accuracy
from sklearn.metrics import  accuracy_score
print("Accuracy of the model is: "+str(accuracy_score(y_test, y_pred)*100)+'%')

Accuracy of the model is: 100.0%


In [127]:
print('\n Confusion matrix')
print(metrics.confusion_matrix(y_test,y_pred))


 Confusion matrix
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
